name: Build Contracts

on: [push]

jobs:
  build-contracts:

    name: Build smart contracts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Setup NodeJS 16
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '16'

      - name: Show NodeJS version
        run: npm --version

      - name: Install Truffle
        run: npm install truffle -g

      - name: Install Dependencies
        run: cd blockchain && npm ci

      - name: Run tests & Generate coverage
        run: cd blockchain && truffle run coverage

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./blockchain/coverage/lcov.info
